# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        key: ${{secrets.GOOGLE_CLOUD_VM_SSH}}
        host: ${{secrets.GOOGLE_CLOUD_VM_IP}}
        username: ${{secrets.GOOGLE_CLOUD_VM_USERNAME}}
        script: |
          pm2 delete all
          cd /home/g12113113/MooApi
          git pull
          yarn install
          yarn run build
          pm2 start dist/index.js
          
          
        
